// angular-frontend/src/app/components/layout/main-layout/main-layout.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-main-layout',
  templateUrl: './main-layout.component.html',
  styleUrls: ['./main-layout.component.scss']
})
export class MainLayoutComponent {
  @Input() showSidebar: boolean = true;
}


<div class="min-h-screen flex flex-col bg-gray-50 dark:bg-gray-900">
  <app-navbar></app-navbar>
  <div class="flex flex-1">
    <app-sidebar *ngIf="showSidebar"></app-sidebar>
    <main class="flex-1 p-4 md:p-6 max-w-7xl mx-auto w-full dark:text-gray-100">
      <router-outlet></router-outlet>
    </main>
  </div>
</div>

// newFront/src/components/Layout/MainLayout.jsx

import { ReactNode } from  "react";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";
import { Toaster } from  "@/components/ui/toaster";



const MainLayout = ({ children, showSidebar = true }) => {
  return (
    <div className="min-h-screen flex flex-col bg-recipe-light dark:bg-gray-900">
      <Navbar />
      <div className="flex flex-1">
        {showSidebar && <Sidebar />}
        <main className="flex-1 p-4 md:p-6 max-w-7xl mx-auto w-full dark:text-gray-100">
          {children}
        </main>
      </div>
      <Toaster />
    </div>
  );
};

export default MainLayout;
