// angular-frontend/src/app/components/layout/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { map } from 'rxjs/operators';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  user$ = this.authService.user$;
  isAuthenticated$ = this.authService.token$.pipe(map(token => !!token));
  searchTerm: string = '';

  constructor(
    private router: Router,
    private authService: AuthService
  ) {}

  handleSearch(event: Event): void {
    event.preventDefault();
    if (this.searchTerm.trim()) {
      this.router.navigate(['/'], { queryParams: { q: this.searchTerm.trim() } });
    }
  }

  logout(): void {
    this.authService.logout();
  }
}


<nav class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-30">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Logo -->
      <div class="flex-shrink-0 flex items-center">
        <a routerLink="/" class="flex items-center gap-2">
          <span class="font-bold text-xl hidden md:inline">Recipito</span>
        </a>
      </div>

      <!-- Search bar - hidden on mobile -->
      <div class="hidden md:block flex-1 max-w-md mx-8">
        <form (ngSubmit)="handleSearch($event)" class="relative">
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg class="h-4 w-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
              </svg>
            </div>
            <input
              type="text"
              placeholder="Search recipes..."
              class="pl-10 w-full px-4 py-2 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              [(ngModel)]="searchTerm"
              [ngModelOptions]="{standalone: true}"
            />
          </div>
        </form>
      </div>

      <!-- Desktop navigation -->
      <div class="hidden md:flex items-center space-x-4">
        <ng-container *ngIf="isAuthenticated$ | async; else notAuthenticated">
          <a routerLink="/create" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
            New Recipe
          </a>
          <a routerLink="/meal-plan" class="px-4 py-2 text-gray-700 hover:text-gray-900">
            Meal Plan
          </a>
          <div class="relative">
            <button class="p-1 rounded-full">
              <div class="h-8 w-8 rounded-full bg-gray-200 flex items-center justify-center">
                <span class="text-sm font-semibold">
                  {{ (user$ | async)?.username?.[0]?.toUpperCase() || 'U' }}
                </span>
              </div>
            </button>
          </div>
          <button (click)="logout()" class="px-4 py-2 text-gray-700 hover:text-gray-900">
            Log out
          </button>
        </ng-container>
        <ng-template #notAuthenticated>
          <a routerLink="/login" class="px-4 py-2 text-gray-700 hover:text-gray-900">Log in</a>
          <a routerLink="/register" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">Sign up</a>
        </ng-template>
      </div>

      <!-- Mobile menu button -->
      <div class="flex md:hidden">
        <button class="inline-flex items-center justify-center p-2 rounded-md text-gray-600">
          <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</nav>

// newFront/src/components/Layout/Navbar.jsx
import { Link, useNavigate, useLocation } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { 
  Bell, 
  SearchIcon as Search, 
  Menu,
  User,
  PlusCircle,
  Settings,
  Bookmark,
  LogOut
} from "lucide-react";
import { useState, useRef, useEffect } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

const Navbar = () => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const location = useLocation();
  const queryParams = new URLSearchParams(location.search);
  const searchQuery = queryParams.get("q") || "";
  const [searchTerm, setSearchTerm] = useState(searchQuery);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [suggestions, setSuggestions] = useState([]);
  const searchRef = useRef(null);
  const { user, isAuthenticated, logout, isLoading } = useAuth();
  const navigate = useNavigate();

  const handleSearch = (e) => {
    e.preventDefault();
    if (searchTerm.trim()) {
      // Navigate to home page with search query parameter
      navigate(`/?q=${encodeURIComponent(searchTerm.trim())}`);
      setShowSuggestions(false);
    }
  };

  const handleSuggestionClick = (recipeId) => {
    navigate(`/recipe/${recipeId}`);
    setShowSuggestions(false);
    setSearchTerm("");
  };
  
  // Clear search when clicking on the home link
  const handleHomeClick = () => {
    setSearchTerm("");
    navigate('/');
  };

  // Update search term when URL query parameter changes
  useEffect(() => {
    setSearchTerm(searchQuery);
  }, [searchQuery]);

  useEffect(() => {
    const updateSuggestions = () => {
      if (searchTerm.trim().length < 2) {
        setSuggestions([]);
        return;
      }

      // Get all posts from the backend
      fetch('http://localhost:2059/api/v1/posts')
        .then(response => response.json())
        .then(data => {
          const allRecipes = data.data.posts;
          const matchedRecipes = allRecipes
            .filter(recipe => 
              recipe.title.toLowerCase().includes(searchTerm.toLowerCase())
            )
            .slice(0, 5) // Limit to 5 suggestions
            .map(recipe => ({ id: recipe._id, title: recipe.title }));

          setSuggestions(matchedRecipes);
        })
        .catch(error => {
          console.error('Error fetching posts:', error);
          setSuggestions([]);
        });
    };

    updateSuggestions();
  }, [searchTerm]);

  // Close suggestions when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (searchRef.current && !searchRef.current.contains(event.target)) {
        setShowSuggestions(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  return (
    <nav className={`bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-30 ${isLoading ? 'opacity-50 cursor-wait' : ''}`}>
      {isLoading && (
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-recipe-primary"></div>
        </div>
      )}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          {/* Logo and brand */}
          <div className="flex-shrink-0 flex items-center">
            <Link to="/" className="flex items-center gap-2" onClick={handleHomeClick}>
             
              <span className="font-bold text-xl hidden md:inline">Recipito</span>
            </Link>
          </div>

          {/* Search bar - hidden on mobile */}
          <div className="hidden md:block flex-1 max-w-md mx-8 relative">
            <form onSubmit={handleSearch} ref={searchRef}>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Search className="h-4 w-4 text-gray-400" />
                </div>
                <Input
                  type="text"
                  placeholder="Search recipes..."
                  className="pl-10 w-full bg-gray-50 dark:bg-gray-700 border-gray-200 dark:border-gray-600 focus:border-recipe-primary"
                  value={searchTerm}
                  onChange={(e) => {
                    setSearchTerm(e.target.value);
                    setShowSuggestions(true);
                  }}
                  onFocus={() => setShowSuggestions(true)}
                />
                <Button 
                  type="submit" 
                  variant="ghost" 
                  size="sm" 
                  className="absolute right-1 top-1/2 transform -translate-y-1/2"
                >
                  <Search className="h-4 w-4" />
                </Button>
              </div>
              
              {/* Search suggestions */}
              {showSuggestions && suggestions.length > 0 && (
                <div className="absolute mt-1 w-full bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-md shadow-lg z-50">
                  <ul className="py-1">
                    {suggestions.map((suggestion) => (
                      <li 
                        key={suggestion.id}
                        className="px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700 cursor-pointer text-gray-800 dark:text-gray-200"
                        onClick={() => handleSuggestionClick(suggestion.id)}
                      >
                        {suggestion.title}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </form>
          </div>

          {/* Desktop navigation */}
          <div className="hidden md:flex items-center space-x-4">
            {isAuthenticated ? (
              <>
               
                <Button className="bg-recipe-primary hover:bg-recipe-primary/90" size="sm" asChild>
                  <Link to="/create">
                    <PlusCircle className="h-4 w-4 mr-2" />
                    New Recipe
                  </Link>
                </Button>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" className="p-1">
                      <Avatar>
                        <AvatarImage 
                          src={user?.avatar || 'https://i.pravatar.cc/150'} 
                          alt={user?.username || 'User'} 
                        />
                        <AvatarFallback>{user?.username?.[0]?.toUpperCase() || 'U'}</AvatarFallback>
                      </Avatar>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem asChild>
                      <Link to={`/profile/${user?.id || ''}`}>
                        <User className="h-4 w-4 mr-2" />
                        Profile
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <Link to="/saved">
                        <Bookmark className="h-4 w-4 mr-2" />
                        Saved Recipes
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem asChild>
                      <Link to="/settings">
                        <Settings className="h-4 w-4 mr-2" />
                        Settings
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onClick={logout}>
                      <LogOut className="h-4 w-4 mr-2" />
                      Log out
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </>
            ) : (
              <>
                <Button variant="ghost" asChild>
                  <Link to="/login">Log in</Link>
                </Button>
                <Button className="bg-recipe-primary hover:bg-recipe-primary/90" asChild>
                  <Link to="/register">Sign up</Link>
                </Button>
              </>
            )}
          </div>

          {/* Mobile menu button */}
          <div className="flex md:hidden">
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="inline-flex items-center justify-center p-2 rounded-md text-gray-600 dark:text-gray-300 hover:text-recipe-primary"
            >
              <Menu className="h-6 w-6" />
            </button>
          </div>
        </div>
      </div>

      {/* Mobile menu */}
      {mobileMenuOpen && (
        <div className="md:hidden bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-4">
          <form onSubmit={handleSearch} className="mb-4" ref={searchRef}>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-gray-400" />
              </div>
              <Input
                type="text"
                placeholder="Search recipes..."
                className="pl-10 w-full bg-gray-50 dark:bg-gray-700 border-gray-200 dark:border-gray-600"
                value={searchTerm}
                onChange={(e) => {
                  setSearchTerm(e.target.value);
                  setShowSuggestions(true);
                }}
                onFocus={() => setShowSuggestions(true)}
              />
              <Button 
                type="submit" 
                variant="ghost" 
                size="sm" 
                className="absolute right-1 top-1/2 transform -translate-y-1/2"
              >
                <Search className="h-4 w-4" />
              </Button>
            </div>
            
            {/* Mobile search suggestions */}
            {showSuggestions && suggestions.length > 0 && (
              <div className="mt-1 w-full bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-md shadow-lg z-50">
                <ul className="py-1">
                  {suggestions.map((suggestion) => (
                    <li 
                      key={suggestion.id}
                      className="px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700 cursor-pointer text-gray-800 dark:text-gray-200"
                      onClick={() => handleSuggestionClick(suggestion.id)}
                    >
                      {suggestion.title}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </form>
          {isAuthenticated ? (
            <div className="space-y-3">
              <Button className="w-full justify-start" asChild>
                <Link to={`/profile/${user?.id || ''}`}>
                  <User className="mr-2 h-4 w-4" />
                  Profile
                </Link>
              </Button>
              <Button className="w-full justify-start" variant="ghost" asChild>
                <Link to="/notifications">
                  <Bell className="mr-2 h-4 w-4" />
                  Notifications
                </Link>
              </Button>
              <Button className="w-full justify-start" variant="ghost" asChild>
                <Link to="/saved">
                  <Bell className="mr-2 h-4 w-4" />
                  Saved Recipes
                </Link>
              </Button>
              <Button className="w-full justify-start" variant="ghost" asChild>
                <Link to="/settings">
                  <Settings className="mr-2 h-4 w-4" />
                  Settings
                </Link>
              </Button>
              <Button className="w-full bg-recipe-primary hover:bg-recipe-primary/90" asChild>
                <Link to="/create">
                  <PlusCircle className="mr-2 h-4 w-4" />
                  New Recipe
                </Link>
              </Button>
              <Button className="w-full" variant="outline" onClick={logout}>
                <LogOut className="mr-2 h-4 w-4" />
                Log out
              </Button>
            </div>
          ) : (
            <div className="space-y-2">
              <Button className="w-full" variant="ghost" asChild>
                <Link to="/login">Log in</Link>
              </Button>
              <Button className="w-full bg-recipe-primary hover:bg-recipe-primary/90" asChild>
                <Link to="/register">Sign up</Link>
              </Button>
            </div>
          )}
        </div>
      )}
    </nav>
  );
};

export default Navbar;
