// angular-frontend/src/app/components/create-recipe/create-recipe.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-create-recipe',
  templateUrl: './create-recipe.component.html',
  styleUrls: ['./create-recipe.component.scss']
})
export class CreateRecipeComponent {
  recipeForm: FormGroup;
  imagePreview: string | null = null;
  isSubmitting: boolean = false;

  // Cuisine options
  cuisineOptions = [
    'Italian',
    'Mexican',
    'Chinese',
    'Indian',
    'Japanese',
    'French',
    'American',
    'Mediterranean',
    'Thai',
    'Korean',
    'Greek',
    'Spanish',
    'Middle Eastern',
    'Vietnamese',
    'Caribbean',
    'African',
    'International',
    'Other'
  ];

  // Difficulty options
  difficultyOptions = ['Easy', 'Medium', 'Hard'];

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private apiService: ApiService,
    private authService: AuthService
  ) {
    this.recipeForm = this.fb.group({
      title: ['', Validators.required],
      description: ['', Validators.required],
      cuisine: ['', Validators.required], // Added cuisine field
      difficulty: ['', Validators.required], // Added difficulty field
      prepTime: ['', [Validators.required, Validators.min(0)]],
      cookTime: ['', [Validators.required, Validators.min(0)]],
      servings: ['', [Validators.required, Validators.min(1)]],
      ingredients: this.fb.array([
        this.fb.group({
          name: ['', Validators.required],
          amount: ['', Validators.required]
        })
      ]),
      instructions: this.fb.array([
        this.fb.control('', Validators.required)
      ]),
      tags: ['', Validators.required],
      image: [null, Validators.required]
    });
  }

  get ingredients(): FormArray {
    return this.recipeForm.get('ingredients') as FormArray;
  }

  get instructions(): FormArray {
    return this.recipeForm.get('instructions') as FormArray;
  }

  addIngredient(): void {
    this.ingredients.push(this.fb.group({
      name: ['', Validators.required],
      amount: ['', Validators.required]
    }));
  }

  removeIngredient(index: number): void {
    if (this.ingredients.length > 1) {
      this.ingredients.removeAt(index);
    }
  }

  addInstruction(): void {
    this.instructions.push(this.fb.control('', Validators.required));
  }

  removeInstruction(index: number): void {
    if (this.instructions.length > 1) {
      this.instructions.removeAt(index);
    }
  }

  onImageSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      const file = input.files[0];
      this.recipeForm.patchValue({ image: file });
      
      const reader = new FileReader();
      reader.onloadend = () => {
        this.imagePreview = reader.result as string;
      };
      reader.readAsDataURL(file);
    }
  }

  onSubmit(): void {
    if (this.recipeForm.valid) {
      this.isSubmitting = true;
      const formValue = this.recipeForm.value;
      
      const formData = new FormData();
      formData.append('title', formValue.title);
      formData.append('description', formValue.description);
      formData.append('cuisine', formValue.cuisine); // Use selected cuisine
      formData.append('difficulty', formValue.difficulty); // Use selected difficulty
      formData.append('servings', formValue.servings);
      formData.append('cookingTime', (parseInt(formValue.prepTime) + parseInt(formValue.cookTime)).toString());
      formData.append('prepTime', formValue.prepTime);
      formData.append('diet', 'Regular');
      formData.append('image', formValue.image);
      
      formValue.ingredients.forEach((ingredient: any, index: number) => {
        formData.append(`ingredients[${index}][name]`, ingredient.name);
        formData.append(`ingredients[${index}][quantity]`, ingredient.amount);
      });
      
      formValue.instructions.forEach((instruction: string, index: number) => {
        formData.append(`instructions[${index}]`, instruction);
      });
      
      const tagsArray = formValue.tags.split(',').map((t: string) => t.trim()).filter(Boolean);
      formData.append('tags', JSON.stringify(tagsArray));

      this.apiService.createPost(formData).subscribe({
        next: () => {
          alert('Recipe created successfully!');
          this.router.navigate(['/']);
        },
        error: (error: any) => {
          alert(error.error?.message || 'Failed to create recipe');
          this.isSubmitting = false;
        }
      });
    }
  }
}
<div class="max-w-3xl mx-auto">
  <h1 class="text-3xl font-bold mb-6">Create Recipe</h1>
  
  <form [formGroup]="recipeForm" (ngSubmit)="onSubmit()" class="space-y-8">
    <!-- Title -->
    <div>
      <label for="title" class="block mb-2">Recipe Title</label>
      <input
        id="title"
        type="text"
        formControlName="title"
        placeholder="E.g., Homemade Cookies"
        class="w-full px-4 py-2 border rounded-md"
      />
      <div *ngIf="recipeForm.get('title')?.invalid && recipeForm.get('title')?.touched" 
           class="text-red-500 text-sm mt-1">
        Title is required
      </div>
    </div>

    <!-- Description -->
    <div>
      <label for="description" class="block mb-2">Description</label>
      <textarea
        id="description"
        formControlName="description"
        placeholder="Describe your recipe..."
        class="w-full px-4 py-2 border rounded-md"
        rows="4"
      ></textarea>
      <div *ngIf="recipeForm.get('description')?.invalid && recipeForm.get('description')?.touched" 
           class="text-red-500 text-sm mt-1">
        Description is required
      </div>
    </div>

    <!-- Cuisine & Difficulty -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        <label for="cuisine" class="block mb-2">Cuisine</label>
        <select
          id="cuisine"
          formControlName="cuisine"
          class="w-full px-4 py-2 border rounded-md"
        >
          <option value="" disabled selected>Select cuisine</option>
          <option *ngFor="let cuisine of cuisineOptions" [value]="cuisine">
            {{ cuisine }}
          </option>
        </select>
        <div *ngIf="recipeForm.get('cuisine')?.invalid && recipeForm.get('cuisine')?.touched" 
             class="text-red-500 text-sm mt-1">
          Cuisine is required
        </div>
      </div>
      <div>
        <label for="difficulty" class="block mb-2">Difficulty</label>
        <select
          id="difficulty"
          formControlName="difficulty"
          class="w-full px-4 py-2 border rounded-md"
        >
          <option value="" disabled selected>Select difficulty</option>
          <option *ngFor="let diff of difficultyOptions" [value]="diff">
            {{ diff }}
          </option>
        </select>
        <div *ngIf="recipeForm.get('difficulty')?.invalid && recipeForm.get('difficulty')?.touched" 
             class="text-red-500 text-sm mt-1">
          Difficulty is required
        </div>
      </div>
    </div>

    <!-- Prep/Cook/Servings -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div>
        <label for="prepTime" class="block mb-2">Prep Time (mins)</label>
        <input
          id="prepTime"
          type="number"
          formControlName="prepTime"
          min="0"
          class="w-full px-4 py-2 border rounded-md"
        />
        <div *ngIf="recipeForm.get('prepTime')?.invalid && recipeForm.get('prepTime')?.touched" 
             class="text-red-500 text-sm mt-1">
          Prep time is required
        </div>
      </div>
      <div>
        <label for="cookTime" class="block mb-2">Cook Time (mins)</label>
        <input
          id="cookTime"
          type="number"
          formControlName="cookTime"
          min="0"
          class="w-full px-4 py-2 border rounded-md"
        />
        <div *ngIf="recipeForm.get('cookTime')?.invalid && recipeForm.get('cookTime')?.touched" 
             class="text-red-500 text-sm mt-1">
          Cook time is required
        </div>
      </div>
      <div>
        <label for="servings" class="block mb-2">Servings</label>
        <input
          id="servings"
          type="number"
          formControlName="servings"
          min="1"
          class="w-full px-4 py-2 border rounded-md"
        />
        <div *ngIf="recipeForm.get('servings')?.invalid && recipeForm.get('servings')?.touched" 
             class="text-red-500 text-sm mt-1">
          Servings is required
        </div>
      </div>
    </div>

    <!-- Ingredients -->
    <div>
      <label class="block mb-2">Ingredients</label>
      <div formArrayName="ingredients">
        <div *ngFor="let ingredient of ingredients.controls; let i = index" 
             [formGroupName]="i" 
             class="flex gap-2 mb-4">
          <input
            formControlName="amount"
            placeholder="Amount"
            class="flex-1 px-4 py-2 border rounded-md"
          />
          <input
            formControlName="name"
            placeholder="Ingredient"
            class="flex-1 px-4 py-2 border rounded-md"
          />
          <button
            type="button"
            (click)="removeIngredient(i)"
            [disabled]="ingredients.length === 1"
            class="px-4 py-2 bg-red-500 text-white rounded-md disabled:opacity-50"
          >
            Remove
          </button>
        </div>
      </div>
      <button
        type="button"
        (click)="addIngredient()"
        class="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md"
      >
        Add Ingredient
      </button>
    </div>

    <!-- Instructions -->
    <div>
      <label class="block mb-2">Instructions</label>
      <div formArrayName="instructions">
        <div *ngFor="let instruction of instructions.controls; let i = index" 
             class="flex gap-2 mb-4">
          <textarea
            [formControlName]="i"
            [placeholder]="'Step ' + (i + 1)"
            class="flex-1 px-4 py-2 border rounded-md"
            rows="3"
          ></textarea>
          <button
            type="button"
            (click)="removeInstruction(i)"
            [disabled]="instructions.length === 1"
            class="px-4 py-2 bg-red-500 text-white rounded-md disabled:opacity-50"
          >
            Remove
          </button>
        </div>
      </div>
      <button
        type="button"
        (click)="addInstruction()"
        class="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md"
      >
        Add Step
      </button>
    </div>

    <!-- Tags -->
    <div>
      <label for="tags" class="block mb-2">Tags (comma separated)</label>
      <input
        id="tags"
        type="text"
        formControlName="tags"
        placeholder="e.g. dessert, vegan, quick"
        class="w-full px-4 py-2 border rounded-md"
      />
      <div *ngIf="recipeForm.get('tags')?.invalid && recipeForm.get('tags')?.touched" 
           class="text-red-500 text-sm mt-1">
        At least one tag is required
      </div>
    </div>

    <!-- Image -->
    <div>
      <label class="block mb-2">Recipe Image</label>
      <label for="image-upload" class="inline-block px-4 py-2 bg-blue-500 text-white rounded cursor-pointer hover:bg-blue-600 m-4">
        Select Image
      </label>
      <input
        id="image-upload"
        name="image"
        type="file"
        accept="image/*"
        class="hidden"
        (change)="onImageSelected($event)"
      />
      <div *ngIf="recipeForm.get('image')?.value" 
           class="bg-gray-100 px-3 py-1 rounded text-sm mt-2 inline-block">
        {{ recipeForm.get('image')?.value?.name }}
      </div>
      <div *ngIf="imagePreview" 
           class="w-full bg-gray-50 rounded mt-4 flex justify-center items-center border border-gray-200" 
           style="min-height: 200px;">
        <img [src]="imagePreview" alt="Preview" class="w-full h-auto object-contain rounded" />
      </div>
      <div *ngIf="recipeForm.get('image')?.invalid && recipeForm.get('image')?.touched" 
           class="text-red-500 text-sm mt-1">
        Image is required
      </div>
    </div>

    <!-- Submit -->
    <button
      type="submit"
      [disabled]="isSubmitting || recipeForm.invalid"
      class="px-6 py-2 bg-blue-500 text-white rounded-md disabled:opacity-50"
    >
      <span *ngIf="isSubmitting">Publishing...</span>
      <span *ngIf="!isSubmitting">Publish Recipe</span>
    </button>
  </form>
</div>

// newFront/src/pages/CreateRecipe.jsx
import { useNavigate } from "react-router-dom";
import MainLayout from "@/components/Layout/MainLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/use-toast";
import { Loader2 } from "lucide-react";
import axios from "axios";
import { useAuth } from "@/contexts/AuthContext";
import { Formik, Form, Field, FieldArray, ErrorMessage } from "formik";
import * as Yup from "yup";
import { useState } from "react";

const API_URL = `${import.meta.env.VITE_API_URL}`;

const validationSchema = Yup.object({
  title: Yup.string().required("Title is required"),
  description: Yup.string().required("Description is required"),
  prepTime: Yup.number().min(0).required("Prep time is required"),
  cookTime: Yup.number().min(0).required("Cook time is required"),
  servings: Yup.number().min(1).required("Servings is required"),

  instructions: Yup.array()
    .of(Yup.string().required("Instruction required"))
    .min(1, "At least one instruction"),
  tags: Yup.string().required("At least one tag is required"),
  image: Yup.mixed().required("Image is required"),
});

const initialValues = {
  title: "",
  description: "",
  prepTime: "",
  cookTime: "",
  servings: "",
  ingredients: [{ name: "", amount: "" }],
  instructions: [""],
  tags: "",
  image: null,
};

const CreateRecipe = () => {
  const { getAuthHeader } = useAuth();
  const { toast } = useToast();
  const navigate = useNavigate();
  const [imagePreview, setImagePreview] = useState(null);

  return (
    <MainLayout>
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-6">Create Recipe</h1>
        <Formik
          initialValues={initialValues}
          validationSchema={validationSchema}
          onSubmit={async (values, { setSubmitting }) => {
            try {
              const formData = new FormData();
              formData.append("title", values.title);
              formData.append("description", values.description);
              formData.append("cuisine", "International");
              formData.append("difficulty", "Medium");
              formData.append("servings", values.servings);
              formData.append("cookingTime", parseInt(values.prepTime) + parseInt(values.cookTime));
              formData.append("prepTime", values.prepTime);
              formData.append("diet", "Regular");
              formData.append("image", values.image);
              values.ingredients.forEach((ingredient, index) => {
                formData.append(`ingredients[${index}][name]`, ingredient.name);
                formData.append(`ingredients[${index}][quantity]`, ingredient.amount);
              });
              values.instructions.forEach((instruction, index) => {
                formData.append(`instructions[${index}]`, instruction);
              });
              // Tags as array
              const tagsArray = values.tags.split(",").map(t => t.trim()).filter(Boolean);
              formData.append("tags", JSON.stringify(tagsArray));
              await axios.post(`${API_URL}/posts`, formData, {
                headers: {
                  "Content-Type": "multipart/form-data",
                  ...getAuthHeader(),
                },
              });
              toast({
                title: "Recipe created!",
                description: "Your recipe has been published successfully.",
              });
              navigate("/");
            } catch (error) {
              toast({
                title: "Error",
                description: error.response?.data?.message || "Failed to create recipe",
                variant: "destructive",
              });
            } finally {
              setSubmitting(false);
            }
          }}
        >
          {({ values, setFieldValue, isSubmitting }) => (
            <Form className="space-y-8">
              {/* Title */}
              <div>
                <Label htmlFor="title">Recipe Title</Label>
                <Field as={Input} name="title" placeholder="E.g., Homemade Cookies" />
                <ErrorMessage name="title" component="div" className="text-red-500 text-sm" />
              </div>
              {/* Description */}
              <div>
                <Label htmlFor="description">Description</Label>
                <Field as={Textarea} name="description" placeholder="Describe your recipe..." />
                <ErrorMessage name="description" component="div" className="text-red-500 text-sm" />
              </div>
              {/* Prep/Cook/Servings */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <Label htmlFor="prepTime">Prep Time (mins)</Label>
                  <Field as={Input} name="prepTime" type="number" min="0" />
                  <ErrorMessage name="prepTime" component="div" className="text-red-500 text-sm" />
                </div>
                <div>
                  <Label htmlFor="cookTime">Cook Time (mins)</Label>
                  <Field as={Input} name="cookTime" type="number" min="0" />
                  <ErrorMessage name="cookTime" component="div" className="text-red-500 text-sm" />
                </div>
                <div>
                  <Label htmlFor="servings">Servings</Label>
                  <Field as={Input} name="servings" type="number" min="1" />
                  <ErrorMessage name="servings" component="div" className="text-red-500 text-sm" />
                </div>
              </div>
              {/* Ingredients */}
              <FieldArray name="ingredients">
                {({ push, remove }) => (
                  <div>
                    <Label>Ingredients</Label>
                    {values.ingredients.map((ingredient, idx) => (
                      <div key={idx} className="flex gap-2 mb-4">
                        <Field as={Input} name={`ingredients[${idx}].amount`} placeholder="Amount" />
                        <Field as={Input} name={`ingredients[${idx}].name`} placeholder="Ingredient" />
                        <Button
                          type="button"
                          onClick={() => remove(idx)}
                          disabled={values.ingredients.length === 1}
                        >
                          Remove
                        </Button>
                      </div>
                    ))}
                    <Button
                      type="button"
                      onClick={() => push({ name: "", amount: "" })}
                      className="mt-4"
                    >
                      Add Ingredient
                    </Button>
                    <ErrorMessage name="ingredients" component="div" className="text-red-500 text-sm" />
                  </div>
                )}
              </FieldArray>
              {/* Instructions */}
              <FieldArray name="instructions">
                {({ push, remove }) => (
                  <div>
                    <Label>Instructions</Label>
                    {values.instructions.map((instruction, idx) => (
                      <div key={idx} className="flex gap-2 mb-4">
                        <Field as={Textarea} name={`instructions[${idx}]`} placeholder={`Step ${idx + 1}`} />
                        <Button
                          type="button"
                          onClick={() => remove(idx)}
                          disabled={values.instructions.length === 1}
                        >
                          Remove
                        </Button>
                      </div>
                    ))}
                    <Button
                      type="button"
                      onClick={() => push("")}
                      className="mt-4"
                    >
                      Add Step
                    </Button>
                    <ErrorMessage name="instructions" component="div" className="text-red-500 text-sm" />
                  </div>
                )}
              </FieldArray>
              {/* Tags */}
              <div>
                <Label htmlFor="tags">Tags (comma separated)</Label>
                <Field as={Input} name="tags" placeholder="e.g. dessert, vegan, quick" />
                <ErrorMessage name="tags" component="div" className="text-red-500 text-sm" />
              </div>
              {/* Image */}
              <div>
                <Label>Recipe Image</Label>
                <label htmlFor="image-upload" className="inline-block px-4 py-2 bg-recipe-primary text-white rounded cursor-pointer hover:bg-recipe-primary/90 m-4">
                  Select Image
                </label>
                <input
                  id="image-upload"
                  name="image"
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={e => {
                    setFieldValue("image", e.currentTarget.files[0]);
                    if (e.currentTarget.files[0]) {
                      const reader = new FileReader();
                      reader.onloadend = () => setImagePreview(reader.result);
                      reader.readAsDataURL(e.currentTarget.files[0]);
                    } else {
                      setImagePreview(null);
                    }
                  }}
                />
                {values.image && (
                  <div className="bg-gray-100 px-3 py-1 rounded text-sm mt-2 inline-block">
                    {values.image.name}
                  </div>
                )}
                {imagePreview && (
                  <div className="w-full bg-gray-50 rounded mt-4 flex justify-center items-center border border-gray-200" style={{ minHeight: '200px' }}>
                    <img src={imagePreview} alt="Preview" className="w-full h-auto object-contain rounded" />
                  </div>
                )}
                <ErrorMessage name="image" component="div" className="text-red-500 text-sm" />
              </div>
              {/* Submit */}
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Publishing...
                  </>
                ) : (
                  "Publish Recipe"
                )}
              </Button>
            </Form>
          )}
        </Formik>
      </div>
    </MainLayout>
  );
};

export default CreateRecipe;
