// angular-frontend/src/app/components/explore/explore.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

interface User {
  _id: string;
  username: string;
  profilePicture?: string;
  recipes?: any[];
}

@Component({
  selector: 'app-explore',
  templateUrl: './explore.component.html',
  styleUrls: ['./explore.component.scss']
})
export class ExploreComponent implements OnInit {
  users: User[] = [];
  loading: boolean = true;
  error: string | null = null;
  searchQuery: string = '';
  currentUser: any = null;
  followingMap: { [key: string]: boolean } = {};

  constructor(
    private apiService: ApiService,
    private authService: AuthService,
    private router: Router
  ) {
    this.authService.user$.subscribe(user => {
      this.currentUser = user;
    });
  }

  ngOnInit(): void {
    this.fetchUsers();
  }

  fetchUsers(): void {
    this.loading = true;
    this.error = null;

    this.apiService.getUsers().subscribe({
      next: (response: any) => {
        if (response.status === 'success') {
          this.users = response.data?.data || response.data?.users || [];
        } else {
          this.users = [];
        }
        this.loading = false;
      },
      error: (err: any) => {
        console.error('Error fetching users:', err);
        this.error = 'Failed to load users. Please try again later.';
        this.users = [];
        this.loading = false;
      }
    });
  }

  get filteredUsers(): User[] {
    if (!this.searchQuery.trim()) {
      return this.users;
    }
    return this.users.filter(user => 
      user?.username?.toLowerCase().includes(this.searchQuery.toLowerCase())
    );
  }

  clearSearch(): void {
    this.searchQuery = '';
  }

  viewProfile(userId: string): void {
    this.router.navigate(['/profile', userId]);
  }

  toggleFollow(userId: string, event: Event): void {
    event.stopPropagation();
    if (!this.currentUser) {
      this.router.navigate(['/login']);
      return;
    }

    this.apiService.followUser(userId).subscribe({
      next: (response: any) => {
        if (response.status === 'success') {
          this.followingMap[userId] = !this.followingMap[userId];
        }
      },
      error: (err: any) => {
        console.error('Error toggling follow:', err);
      }
    });
  }

  isFollowing(userId: string): boolean {
    return this.followingMap[userId] || false;
  }
}


<div class="container py-8 max-w-4xl">
  <div class="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4">
    <h1 class="text-3xl font-bold">Explore Users</h1>
    
    <div class="relative w-full md:w-72">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="h-4 w-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
        </svg>
      </div>
      <input
        type="text"
        placeholder="Search users..."
        class="w-full pl-10 pr-10 px-4 py-2 border rounded-md"
        [(ngModel)]="searchQuery"
      />
      <button
        *ngIf="searchQuery"
        (click)="clearSearch()"
        class="absolute inset-y-0 right-0 flex items-center pr-3"
        aria-label="Clear search"
      >
        <svg class="h-4 w-4 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>
  </div>
  
  <div *ngIf="error" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
    {{ error }}
  </div>

  <div *ngIf="loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <div *ngFor="let i of [1,2,3,4,5,6]" class="bg-white rounded-lg shadow p-6">
      <div class="flex items-center space-x-4">
        <div class="h-12 w-12 rounded-full bg-gray-200 animate-pulse"></div>
        <div class="space-y-2">
          <div class="h-4 w-24 bg-gray-200 rounded animate-pulse"></div>
          <div class="h-3 w-32 bg-gray-200 rounded animate-pulse"></div>
        </div>
      </div>
      <div class="mt-4">
        <div class="h-8 w-full bg-gray-200 rounded animate-pulse"></div>
      </div>
    </div>
  </div>

  <div *ngIf="!loading">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div *ngFor="let user of filteredUsers; let i = index" 
           class="bg-white rounded-lg shadow p-6 hover:shadow-md transition-shadow">
        <div class="flex items-center space-x-4">
          <div class="h-12 w-12 rounded-full bg-gray-200 flex items-center justify-center overflow-hidden">
            <img *ngIf="user?.profilePicture" 
                 [src]="user.profilePicture?.startsWith('http') ? user.profilePicture : 'http://localhost:3000' + user.profilePicture" 
                 [alt]="user?.username || 'User'"
                 class="w-full h-full object-cover" />
            <span *ngIf="!user?.profilePicture" class="text-gray-600 font-semibold">
              {{ (user?.username || 'U').slice(0, 2).toUpperCase() }}
            </span>
          </div>
          <div>
            <h3 class="font-medium">{{ user?.username || 'Unknown User' }}</h3>
            <p class="text-sm text-gray-500">
              {{ user?.recipes?.length || 0 }} recipes
            </p>
          </div>
        </div>
        <div class="mt-4 flex gap-2">
          <button 
            *ngIf="currentUser && currentUser._id !== user._id"
            (click)="toggleFollow(user._id, $event)"
            [class.bg-blue-500]="isFollowing(user._id)"
            [class.text-white]="isFollowing(user._id)"
            [class.bg-gray-200]="!isFollowing(user._id)"
            class="flex-1 px-4 py-2 rounded-md hover:bg-gray-300"
          >
            {{ isFollowing(user._id) ? 'Following' : 'Follow' }}
          </button>
          <button 
            (click)="viewProfile(user._id)"
            class="flex-1 px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50"
          >
            View Profile
          </button>
        </div>
      </div>
    </div>
    
    <div *ngIf="filteredUsers.length === 0 && searchQuery" 
         class="text-center py-12 bg-gray-50 rounded-lg mt-6">
      <h3 class="text-xl font-medium mb-2">No users found</h3>
      <p class="text-gray-500">
        No users match your search for "{{ searchQuery }}"
      </p>
      <button 
        (click)="clearSearch()"
        class="mt-4 px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50"
      >
        Clear Search
      </button>
    </div>

    <div *ngIf="!loading && users.length === 0 && !searchQuery" 
         class="text-center py-12 bg-gray-50 rounded-lg mt-6">
      <h3 class="text-xl font-medium mb-2">No users found</h3>
      <p class="text-gray-500">
        There are no users registered in the system yet.
      </p>
    </div>
  </div>
</div>

// newFront/src/pages/Explore.jsx
import { useState, useEffect, useMemo } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import MainLayout from "@/components/Layout/MainLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Input } from "@/components/ui/input";
import { Search, X } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

const API_URL = "http://localhost:2059/api/v1";

const Explore = () => {
  const { getAuthHeader } = useAuth();
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");
  
  // Filter users based on search query
  const filteredUsers = useMemo(() => {
    if (!searchQuery.trim()) return users;
    
    return users.filter(user => 
      user?.username?.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [users, searchQuery]);

  useEffect(() => {
    const fetchUsers = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`${API_URL}/users`, {
          headers: {
            ...getAuthHeader()
          }
        });

        console.log('Full API response:', response.data);
        
        if (response.data.status === 'success') {
          // Based on the handlerFactory.js, the users will be in response.data.data.data
          const userData = response.data.data.data || [];
          console.log('User data from API:', userData);
          setUsers(userData);
        }
        setLoading(false);
      } catch (err) {
        console.error("Error fetching users:", err);
        setError("Failed to load users. Please try again later.");
        setLoading(false);
      }
    };

    fetchUsers();
  }, [getAuthHeader]);

  // Handle search input change
  const handleSearchChange = (e) => {
    setSearchQuery(e.target.value);
  };

  // Clear search
  const clearSearch = () => {
    setSearchQuery("");
  };

  return (
    <MainLayout>
      <div className="container py-8 max-w-4xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 gap-4">
          <h1 className="text-3xl font-bold">Explore Users</h1>
          
          <div className="relative w-full md:w-72">
            <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <Search className="h-4 w-4 text-gray-400" />
            </div>
            <Input
              type="text"
              placeholder="Search users..."
              className="pl-10 pr-10"
              value={searchQuery}
              onChange={handleSearchChange}
            />
            {searchQuery && (
              <button
                onClick={clearSearch}
                className="absolute inset-y-0 right-0 flex items-center pr-3"
                aria-label="Clear search"
              >
                <X className="h-4 w-4 text-gray-400 hover:text-gray-600" />
              </button>
            )}
          </div>
        </div>
        
        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
            {error}
          </div>
        )}

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <Card key={i} className="overflow-hidden">
                <CardContent className="p-6">
                  <div className="flex items-center space-x-4">
                    <Skeleton className="h-12 w-12 rounded-full" />
                    <div className="space-y-2">
                      <Skeleton className="h-4 w-24" />
                      <Skeleton className="h-3 w-32" />
                    </div>
                  </div>
                  <div className="mt-4">
                    <Skeleton className="h-8 w-full" />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredUsers.map((user, index) => (
                <Card key={user?._id || index} className="overflow-hidden hover:shadow-md transition-shadow">
                  <CardContent className="p-6">
                    <div className="flex items-center space-x-4">
                      <Avatar className="h-12 w-12">
                        <AvatarImage 
                          src={user?.profilePicture ? (user.profilePicture.startsWith('http') ? user.profilePicture : `http://localhost:2059${user.profilePicture}`) : null} 
                          alt={user?.username || 'User'} 
                        />
                        <AvatarFallback>{(user?.username || 'U').slice(0, 2).toUpperCase()}</AvatarFallback>
                      </Avatar>
                      <div>
                        <h3 className="font-medium">{user?.username || 'Unknown User'}</h3>
                        <p className="text-sm text-muted-foreground">
                          {user?.recipes?.length || 0} recipes
                        </p>
                      </div>
                    </div>
                    <div className="mt-4">
                      <Button asChild className="w-full" variant="outline">
                        <Link to={`/profile/${user?._id}`}>View Profile</Link>
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
            
            {filteredUsers.length === 0 && searchQuery && (
              <div className="text-center py-12 bg-muted/20 rounded-lg">
                <h3 className="text-xl font-medium mb-2">No users found</h3>
                <p className="text-muted-foreground">
                  No users match your search for "{searchQuery}"
                </p>
                <Button 
                  variant="outline" 
                  onClick={clearSearch} 
                  className="mt-4"
                >
                  Clear Search
                </Button>
              </div>
            )}
          </>
        )}

        {!loading && users.length === 0 && (
          <div className="text-center py-12 bg-muted/20 rounded-lg">
            <h3 className="text-xl font-medium mb-2">No users found</h3>
            <p className="text-muted-foreground">
              There are no users registered in the system yet.
            </p>
          </div>
        )}
      </div>
    </MainLayout>
  );
};

export default Explore;
