// angular-frontend/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Observable, forkJoin } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { environment } from '../../../environments/environment';

interface Post {
  _id: string;
  title: string;
  description: string;
  ingredients: any[];
  instructions: any[];
  cookingTime: number;
  servings: number;
  difficulty: string;
  cuisine: string;
  author: {
    _id: string;
    username: string;
    profilePicture?: string;
  };
  imageUrl?: string;
  comments: any[];
  likes: string[];
  createdAt: string;
}

interface LikeInfo {
  isLiked: boolean;
  likesCount: number;
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  activeTab: string = 'forYou';
  posts: Post[] = [];
  filteredPosts: Post[] = [];
  searchInput: string = '';
  loading: boolean = true;
  error: string | null = null;
  likesMap: { [key: string]: LikeInfo } = {};
  
  // Filter options
  showFilters: boolean = false;
  selectedCuisine: string = '';
  maxCookingTime: number | null = null;
  ingredientSearch: string = '';
  
  // Available cuisines (will be populated from posts)
  availableCuisines: string[] = [];
  
  user$ = this.authService.user$;
  isAuthenticated$ = this.authService.token$.pipe(map(token => !!token));

  constructor(
    public route: ActivatedRoute,
    public router: Router,
    private apiService: ApiService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.route.queryParams.subscribe(params => {
      const searchQuery = params['q'] || '';
      this.searchInput = searchQuery;
      this.fetchPosts(searchQuery);
    });
  }

  fetchPosts(searchQuery: string): void {
    this.loading = true;
    this.error = null;

    // Request all posts (set high limit to get all)
    this.apiService.getPosts({ limit: 1000 }).subscribe({
      next: (response: any) => {
        const fetchedPosts = response.data.posts;
        
        // Prepend backend URL to image paths
        const postsWithFullImageUrls = fetchedPosts.map((post: Post) => ({
          ...post,
          imageUrl: post.imageUrl ? `${environment.baseUrl}${post.imageUrl}` : undefined
        }));
        
        this.posts = postsWithFullImageUrls;
        
        // Extract available cuisines
        this.extractAvailableCuisines(postsWithFullImageUrls);
        
        // Apply filters
        this.applyFilters();
        
        // Fetch likes status if authenticated
        this.isAuthenticated$.subscribe(isAuth => {
          if (isAuth && postsWithFullImageUrls.length > 0) {
            this.fetchLikesStatus(postsWithFullImageUrls);
          } else {
            this.setupLikesMap(postsWithFullImageUrls);
          }
        });
        
        this.loading = false;
      },
      error: (err: any) => {
        console.error('Error fetching posts:', err);
        this.error = err.message;
        this.loading = false;
      }
    });
  }

  private extractAvailableCuisines(posts: Post[]): void {
    const cuisineSet = new Set<string>();
    posts.forEach(post => {
      if (post.cuisine) {
        cuisineSet.add(post.cuisine);
      }
    });
    this.availableCuisines = Array.from(cuisineSet).sort();
  }

  applyFilters(): void {
    let filtered = [...this.posts];

    // First apply search query (this is separate from other filters)
    if (this.searchInput && this.searchInput.trim()) {
      const query = this.searchInput.toLowerCase();
      filtered = filtered.filter(post => 
        post.title.toLowerCase().includes(query) ||
        post.description.toLowerCase().includes(query)
      );
    }

    // Check if any filters are active
    const hasActiveFilters = this.selectedCuisine || 
                            (this.maxCookingTime !== null && this.maxCookingTime > 0) || 
                            (this.ingredientSearch && this.ingredientSearch.trim());

    // Apply OR logic for cuisine, time, and ingredient filters
    if (hasActiveFilters) {
      filtered = filtered.filter(post => {
        let matchesAnyFilter = false;

        // Check cuisine filter
        if (this.selectedCuisine && post.cuisine === this.selectedCuisine) {
          matchesAnyFilter = true;
        }

        // Check max prep time filter
        if (this.maxCookingTime !== null && this.maxCookingTime > 0 && post.cookingTime <= this.maxCookingTime) {
          matchesAnyFilter = true;
        }

        // Check ingredient filter
        if (this.ingredientSearch && this.ingredientSearch.trim()) {
          const ingredientQuery = this.ingredientSearch.toLowerCase();
          if (post.ingredients.some(ing => ing.name?.toLowerCase().includes(ingredientQuery))) {
            matchesAnyFilter = true;
          }
        }

        return matchesAnyFilter;
      });
    }

    this.filteredPosts = filtered;
  }

  onFilterChange(): void {
    this.applyFilters();
  }

  clearFilters(): void {
    this.selectedCuisine = '';
    this.maxCookingTime = null;
    this.ingredientSearch = '';
    this.applyFilters();
  }

  toggleFilters(): void {
    this.showFilters = !this.showFilters;
  }

  private setupLikesMap(postsArray: Post[]): void {
    const likesMap: { [key: string]: LikeInfo } = {};
    postsArray.forEach(post => {
      likesMap[post._id] = {
        isLiked: false,
        likesCount: post.likes.length
      };
    });
    this.likesMap = likesMap;
  }

  private fetchLikesStatus(postsArray: Post[]): void {
    const user = this.authService.currentUser;
    const fallbackLikesMap: { [key: string]: LikeInfo } = {};
    
    postsArray.forEach(post => {
      const userId = user?._id || user?.id;
      fallbackLikesMap[post._id] = {
        isLiked: userId ? post.likes.some(id => id.toString() === userId.toString()) : false,
        likesCount: post.likes.length
      };
    });

    // Fetch likes for first batch
    const BATCH_SIZE = 5;
    const firstBatch = postsArray.slice(0, BATCH_SIZE);
    const postIds = firstBatch.map(post => post._id);

    if (postIds.length > 0) {
      this.apiService.checkLikes(postIds).subscribe({
        next: (response: any) => {
          if (response.status === 'success') {
            this.likesMap = { ...fallbackLikesMap, ...response.data.likes };
          } else {
            this.likesMap = fallbackLikesMap;
          }
        },
        error: () => {
          this.likesMap = fallbackLikesMap;
        }
      });
    } else {
      this.likesMap = fallbackLikesMap;
    }
  }

  onSearchSubmit(): void {
    if (this.searchInput.trim()) {
      this.router.navigate(['/'], { queryParams: { q: this.searchInput.trim() } });
    } else {
      this.router.navigate(['/']);
    }
  }

  clearSearch(): void {
    this.searchInput = '';
    this.router.navigate(['/']);
  }

  setActiveTab(tab: string): void {
    this.activeTab = tab;
  }

  getSortedPosts(): Post[] {
    if (this.activeTab === 'trending') {
      return [...this.filteredPosts].sort((a, b) => {
        const aLikes = this.likesMap[a._id]?.likesCount || a.likes.length;
        const bLikes = this.likesMap[b._id]?.likesCount || b.likes.length;
        return bLikes - aLikes;
      });
    }
    return this.filteredPosts;
  }

  onLikeUpdate(postId: string, newLikeInfo: LikeInfo): void {
    this.likesMap[postId] = newLikeInfo;
  }
}
<div class="max-w-5xl mx-auto">
  <div class="bg-white p-6 md:p-8 rounded-lg shadow-sm mb-8">
    <div *ngIf="searchInput" class="mb-4 p-2 bg-gray-100 rounded-md">
      <p class="text-sm">
        Showing results for "{{ searchInput }}" ({{ filteredPosts.length }} found)
        <button 
          class="ml-2 p-0 h-auto text-blue-500 hover:underline" 
          (click)="clearSearch()"
        >
          Clear
        </button>
      </p>
    </div>

    <!-- Filter Toggle Button -->
    <div class="mb-4">
      <button 
        (click)="toggleFilters()"
        class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 flex items-center gap-2"
      >
        <span>🔍</span>
        <span>{{ showFilters ? 'Hide Filters' : 'Show Filters' }}</span>
      </button>
    </div>

    <!-- Filters Section -->
    <div *ngIf="showFilters" class="mb-6 p-4 bg-gray-50 rounded-lg">
      <h3 class="font-semibold mb-4">Filter Recipes (OR logic - match any filter)</h3>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <!-- Cuisine Filter -->
        <div>
          <label for="cuisine-filter" class="block text-sm font-medium mb-2">Cuisine</label>
          <select 
            id="cuisine-filter"
            [(ngModel)]="selectedCuisine"
            (change)="onFilterChange()"
            class="w-full px-3 py-2 border rounded-md"
          >
            <option value="">All Cuisines</option>
            <option *ngFor="let cuisine of availableCuisines" [value]="cuisine">
              {{ cuisine }}
            </option>
          </select>
        </div>

        <!-- Max Prep Time Filter -->
        <div>
          <label for="time-filter" class="block text-sm font-medium mb-2">
            Max Cooking Time: {{ maxCookingTime || 'Any' }} min
          </label>
          <input 
            id="time-filter"
            type="range"
            [(ngModel)]="maxCookingTime"
            (input)="onFilterChange()"
            min="0"
            max="180"
            step="15"
            class="w-full"
          />
          <div class="flex justify-between text-xs text-gray-500 mt-1">
            <span>0 min</span>
            <span>180 min</span>
          </div>
        </div>

        <!-- Ingredient Search Filter -->
        <div>
          <label for="ingredient-filter" class="block text-sm font-medium mb-2">Ingredient</label>
          <input 
            id="ingredient-filter"
            type="text"
            [(ngModel)]="ingredientSearch"
            (input)="onFilterChange()"
            placeholder="e.g., chicken, tomato"
            class="w-full px-3 py-2 border rounded-md"
          />
        </div>
      </div>

      <!-- Clear Filters Button -->
      <div class="mt-4 flex items-center gap-4">
        <button 
          (click)="clearFilters()"
          class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300"
        >
          Clear All Filters
        </button>
        <span class="text-sm text-gray-600">
          Showing {{ filteredPosts.length }} of {{ posts.length }} recipes
        </span>
      </div>
    </div>

    <div class="tabs">
      <div class="tabs-list grid w-full md:w-[400px] grid-cols-2 mb-6">
        <button 
          class="tab-trigger"
          [class.active]="activeTab === 'forYou'"
          (click)="setActiveTab('forYou')"
        >
          For You
        </button>
        <button 
          class="tab-trigger"
          [class.active]="activeTab === 'trending'"
          (click)="setActiveTab('trending')"
        >
          Trending
        </button>
      </div>

      <div *ngIf="loading" class="flex justify-center items-center h-64">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900"></div>
      </div>

      <div *ngIf="error" class="text-red-500 text-center p-4">{{ error }}</div>

      <div *ngIf="!loading && !error">
        <!-- No Results Message -->
        <div *ngIf="filteredPosts.length === 0" class="text-center py-12">
          <p class="text-gray-500 text-lg mb-4">No recipes found</p>
          <button 
            (click)="clearFilters(); clearSearch()"
            class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600"
          >
            Clear All Filters
          </button>
        </div>

        <div *ngIf="activeTab === 'forYou' && filteredPosts.length > 0" class="mt-6">
          <div class="grid gap-8 grid-cols-1 md:grid-cols-2">
            <div
              *ngFor="let post of filteredPosts"
              class="bg-white rounded-lg shadow p-4 cursor-pointer hover:shadow-lg transition-shadow"
              (click)="router.navigate(['/recipe', post._id])"
            >
              <img *ngIf="post.imageUrl" [src]="post.imageUrl" [alt]="post.title" class="w-full h-48 object-cover rounded mb-2" />
              <h3 class="font-bold text-lg mb-2">{{ post.title }}</h3>
              <p class="text-gray-600 text-sm mb-2 line-clamp-2">{{ post.description }}</p>
              <div class="mt-2 text-sm text-gray-500 flex items-center gap-4">
                <span>By {{ post.author.username }}</span>
                <span>•</span>
                <span>{{ post.cookingTime }} min</span>
                <span>•</span>
                <span>{{ post.cuisine }}</span>
              </div>
            </div>
          </div>
        </div>

        <div *ngIf="activeTab === 'trending' && filteredPosts.length > 0" class="mt-6">
          <div class="grid gap-8 grid-cols-1 md:grid-cols-2">
            <div
              *ngFor="let post of getSortedPosts()"
              class="bg-white rounded-lg shadow p-4 cursor-pointer hover:shadow-lg transition-shadow"
              (click)="router.navigate(['/recipe', post._id])"
            >
              <img *ngIf="post.imageUrl" [src]="post.imageUrl" [alt]="post.title" class="w-full h-48 object-cover rounded mb-2" />
              <h3 class="font-bold text-lg mb-2">{{ post.title }}</h3>
              <p class="text-gray-600 text-sm mb-2 line-clamp-2">{{ post.description }}</p>
              <div class="mt-2 text-sm text-gray-500 flex items-center gap-4">
                <span>By {{ post.author.username }}</span>
                <span>•</span>
                <span>{{ post.cookingTime }} min</span>
                <span>•</span>
                <span>{{ post.cuisine }}</span>
                <span>•</span>
                <span>{{ (likesMap[post._id]?.likesCount || post.likes.length) }} likes</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// newFront/src/pages/Home.jsx
import { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import MainLayout from "@/components/Layout/MainLayout";
import RecipeCard from "@/components/Recipe/RecipeCard";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search as SearchIcon } from "lucide-react";
import axios from "axios";
import { useAuth } from "@/contexts/AuthContext";

const API_URL = "http://localhost:2059/api/v1";

const Home = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const queryParams = new URLSearchParams(location.search);
  const searchQuery = queryParams.get("q") || "";
  
  const [activeTab, setActiveTab] = useState("forYou");
  const [posts, setPosts] = useState([]);
  const [filteredPosts, setFilteredPosts] = useState([]);
  const [searchInput, setSearchInput] = useState(searchQuery);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [likesMap, setLikesMap] = useState({});
  const { user, isAuthenticated, getAuthHeader } = useAuth();

  // Function to filter posts by title
  const filterPosts = (postsToFilter, query) => {
    if (!query) {
      return postsToFilter;
    }
    
    const lowerCaseQuery = query.toLowerCase();
    return postsToFilter.filter(post => 
      post.title.toLowerCase().includes(lowerCaseQuery)
    );
  };

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`${API_URL}/posts`, {
          headers: {
            ...getAuthHeader() // Add authorization header if user is logged in
          }
        });

        const fetchedPosts = response.data.data.posts;
        setPosts(fetchedPosts);
        
        // Apply search filter if there's a query
        if (searchQuery) {
          setFilteredPosts(filterPosts(fetchedPosts, searchQuery));
        } else {
          setFilteredPosts(fetchedPosts);
        }
        
        // If user is authenticated, fetch like status for all posts
        if (isAuthenticated && fetchedPosts.length > 0) {
          await fetchLikesStatus(fetchedPosts);
        } else {
          // If not authenticated, still set up likes count
          const likesMapFromPosts = {};
          fetchedPosts.forEach(post => {
            likesMapFromPosts[post._id] = {
              isLiked: false,
              likesCount: post.likes.length
            };
          });
          setLikesMap(likesMapFromPosts);
        }
        
        setError(null);
      } catch (err) {
        console.error('Error fetching posts:', err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    
    // Fetch like status for all posts
    const fetchLikesStatus = async (postsArray) => {
      try {
        // Create a fallback likes map in case the API fails
        const fallbackLikesMap = {};
        postsArray.forEach(post => {
          const userId = user?._id || user?.id;
          fallbackLikesMap[post._id] = {
            isLiked: userId ? post.likes.some(id => id.toString() === userId.toString()) : false,
            likesCount: post.likes.length
          };
        });
        
        try {
          // Extract post IDs - limit to smaller batches to avoid URL length issues
          const BATCH_SIZE = 5;
          const firstBatch = postsArray.slice(0, BATCH_SIZE);
          const postIds = firstBatch.map(post => post._id).join(',');
          
          // Fetch like status for the first batch of posts
          const likesResponse = await axios.get(`${API_URL}/posts/check-likes?posts=${postIds}`, {
            headers: {
              ...getAuthHeader()
            }
          });
        
          if (likesResponse.data.status === 'success') {
            console.debug('Received likes map:', likesResponse.data.data.likes);
            // Merge with fallback map for any missing posts
            const combinedMap = { ...fallbackLikesMap, ...likesResponse.data.data.likes };
            setLikesMap(combinedMap);
          } else {
            // Use fallback if API returns success: false
            setLikesMap(fallbackLikesMap);
          }
        } catch (apiErr) {
          console.error('Error fetching likes status from API, using fallback:', apiErr);
          // Use fallback if API call fails
          setLikesMap(fallbackLikesMap);
        }
      } catch (err) {
        console.error('Error in likes processing:', err);
        // If everything fails, just use an empty map
        setLikesMap({});
      }
    };


    
    fetchPosts();
  }, [user, isAuthenticated, getAuthHeader, searchQuery]);
  
  // Handle search input change
  const handleSearchInputChange = (e) => {
    setSearchInput(e.target.value);
  };
  
  // Handle search form submission
  const handleSearchSubmit = (e) => {
    e.preventDefault();
    if (searchInput.trim()) {
      navigate(`/?q=${encodeURIComponent(searchInput.trim())}`);
    } else {
      navigate('/');
    }
  };
  
  // Effect to filter posts when search query changes
  useEffect(() => {
    setFilteredPosts(filterPosts(posts, searchQuery));
  }, [searchQuery, posts]);

  return (
    <MainLayout>
      <div className="max-w-5xl mx-auto">
        <div className="bg-background p-6 md:p-8 rounded-lg shadow-sm mb-8">
          {searchQuery && (
            <div className="mb-4 p-2 bg-muted rounded-md">
              <p className="text-sm">
                Showing results for "{searchQuery}" ({filteredPosts.length} found)
                <Button 
                  variant="link" 
                  className="ml-2 p-0 h-auto" 
                  onClick={() => navigate('/')}
                >
                  Clear
                </Button>
              </p>
            </div>
          )}

          <Tabs defaultValue={activeTab} onValueChange={setActiveTab}>
            <TabsList className="grid w-full md:w-[400px] grid-cols-2">
              <TabsTrigger value="forYou">For You</TabsTrigger>
              <TabsTrigger value="trending">Trending</TabsTrigger>
            </TabsList>

            {loading ? (
              <div className="flex justify-center items-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900"></div>
              </div>
            ) : error ? (
              <div className="text-red-500 text-center p-4">{error}</div>
            ) : (
              <>
                <TabsContent value="forYou" className="mt-6">
                  <div className="grid gap-8 grid-cols-1 md:grid-cols-2">
                    {filteredPosts.map((post) => (
                      <RecipeCard
                        key={post._id}
                        recipe={{
                          id: post._id,
                          title: post.title,
                          description: post.description,
                          ingredients: post.ingredients,
                          instructions: post.instructions.map(
                            (step) => step.step
                          ),
                          cookingTime: post.cookingTime,
                          servings: post.servings,
                          difficulty: post.difficulty,
                          cuisine: post.cuisine,
                          author: {
                            id: post.author._id,
                            username: post.author.username,
                            profilePicture: post.author.profilePicture,
                          },
                          imageUrl: post.imageUrl || `/uploads/posts/${post._id}.jpeg`,
                          comments: post.comments,
                          likes: post.likes,
                          createdAt: post.createdAt,
                        }}
                        likeInfo={likesMap[post._id]}
                        onLikeUpdate={(postId, newLikeInfo) => {
                          setLikesMap(prev => ({
                            ...prev,
                            [postId]: newLikeInfo
                          }));
                        }}
                      />
                    ))}
                  </div>
                </TabsContent>

                <TabsContent value="trending" className="mt-6">
                  <div className="grid gap-8 grid-cols-1 md:grid-cols-2">
                    {filteredPosts
                      .sort((a, b) => {
                        const aLikes = likesMap[a._id]?.likesCount || a.likes.length;
                        const bLikes = likesMap[b._id]?.likesCount || b.likes.length;
                        return bLikes - aLikes;
                      })
                      .map((post) => (
                        <RecipeCard
                          key={post._id}
                          recipe={{
                            id: post._id,
                            title: post.title,
                            description: post.description,
                            ingredients: post.ingredients,
                            instructions: post.instructions.map(
                              (step) => step.step
                            ),
                            cookingTime: post.cookingTime,
                            servings: post.servings,
                            difficulty: post.difficulty,
                            cuisine: post.cuisine,
                            author: {
                              id: post.author._id,
                              username: post.author.username,
                              profilePicture: post.author.profilePicture,
                            },
                            imageUrl: post.imageUrl || `/uploads/posts/${post._id}.jpeg`,
                            likes: post.likes,
                            createdAt: post.createdAt,
                          }}
                          likeInfo={likesMap[post._id]}
                          onLikeUpdate={(postId, newLikeInfo) => {
                            setLikesMap(prev => ({
                              ...prev,
                              [postId]: newLikeInfo
                            }));
                          }}
                        />
                      ))}
                  </div>
                </TabsContent>
              </>
            )}
          </Tabs>
        </div>
      </div>
    </MainLayout>
  );
};

export default Home;
