// angular-frontend/src/app/components/user-profile/user-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { forkJoin } from 'rxjs';
import { catchError, map } from 'rxjs/operators';
import { of } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { environment } from '../../../environments/environment';

interface Recipe {
  _id: string;
  title: string;
  description: string;
  ingredients: any[];
  instructions: any[];
  cookingTime: number;
  servings: number;
  difficulty: string;
  cuisine: string;
  author: {
    _id: string;
    username: string;
    profilePicture?: string;
  };
  imageUrl?: string;
  createdAt: string;
}

interface Profile {
  _id: string;
  username: string;
  profilePicture?: string;
  bio?: string;
  location?: string;
  recipes?: Recipe[];
  savedRecipes?: Recipe[];
}

@Component({
  selector: 'app-user-profile',
  templateUrl: './user-profile.component.html',
  styleUrls: ['./user-profile.component.scss']
})
export class UserProfileComponent implements OnInit {
  profile: Profile | null = null;
  isLoading: boolean = true;
  error: string | null = null;
  isCurrentUser: boolean = false;
  activeTab: string = 'recipes';
  currentUser: any = null;
  isFollowing: boolean = false;
  followersCount: number = 0;
  followingCount: number = 0;

  constructor(
    private route: ActivatedRoute,
    public router: Router,
    private apiService: ApiService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.authService.user$.subscribe((user: any) => {
      this.currentUser = user;
      if (user) {
        this.fetchProfile();
      } else {
        alert('You must be logged in to view profiles');
        this.router.navigate(['/login']);
      }
    });
  }

  // Helper function to add full image URLs
  private addFullImageUrls(recipes: Recipe[]): Recipe[] {
    if (!recipes || !Array.isArray(recipes)) return [];
    return recipes.map(recipe => ({
      ...recipe,
      imageUrl: recipe.imageUrl ? `${environment.baseUrl}${recipe.imageUrl}` : undefined
    }));
  }

  fetchProfile(): void {
    const id = this.route.snapshot.paramMap.get('id');
    const userId = id || this.currentUser?._id || this.currentUser?.id;

    if (!userId) {
      this.error = 'User ID not found';
      this.isLoading = false;
      return;
    }

    this.isCurrentUser = userId === (this.currentUser?._id || this.currentUser?.id);
    this.isLoading = true;
    this.error = null;

    forkJoin([
      this.apiService.getUser(userId).pipe(
        catchError((err: any) => {
          console.error('Error fetching user:', err);
          return of({ status: 'error', data: {} });
        })
      ),
      this.apiService.getUserRecipes(userId).pipe(
        catchError((err: any) => {
          console.error('Error fetching recipes:', err);
          return of({ status: 'error', data: { recipes: [], savedRecipes: [] } });
        })
      )
    ]).subscribe({
      next: ([userResponse, recipesResponse]: any[]) => {
        const userData = userResponse.data?.user || userResponse.data?.data;
        const recipesData = recipesResponse.data || { recipes: [], savedRecipes: [] };

        if (!userData) {
          this.error = 'User data not found';
          this.isLoading = false;
          return;
        }

        // FIXED: Use savedRecipes from the API response
        this.profile = {
          ...userData,
          recipes: this.addFullImageUrls(recipesData.recipes || []),
          savedRecipes: this.addFullImageUrls(recipesData.savedRecipes || [])
        };

        console.log('Profile with saved recipes:', this.profile); // Debug log

        // Check if current user is following this profile
        if (this.currentUser && this.profile) {
          this.isFollowing = userData.followers?.some((f: any) => 
            (f._id || f) === (this.currentUser._id || this.currentUser.id)
          ) || false;
          this.followersCount = userData.followers?.length || 0;
          this.followingCount = userData.following?.length || 0;
        }

        this.isLoading = false;
      },
      error: (err: any) => {
        this.error = err.message || 'Failed to load profile';
        console.error('Error fetching profile:', err);
        this.isLoading = false;
      }
    });
  }

  setActiveTab(tab: string): void {
    this.activeTab = tab;
  }


  createRecipe(): void {
    this.router.navigate(['/create']);
  }

  browseRecipes(): void {
    this.router.navigate(['/']);
  }

  toggleFollow(): void {
    if (!this.currentUser) {
      this.router.navigate(['/']);
      return;
    }

    if (!this.profile) return;

    const profileId = this.profile._id;
    this.apiService.followUser(profileId).subscribe({
      next: (response: any) => {
        if (response.status === 'success') {
          this.isFollowing = !this.isFollowing;
          if (this.isFollowing) {
            this.followersCount++;
          } else {
            this.followersCount = Math.max(0, this.followersCount - 1);
          }
        }
      },
      error: (err: any) => {
        console.error('Error toggling follow:', err);
        alert('Failed to update follow status');
      }
    });
  }
}
<div class="container mx-auto py-8">
  <div *ngIf="isLoading" class="flex items-center justify-center min-h-[80vh]">
    <div class="flex flex-col items-center">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      <p class="mt-4 text-gray-500">Loading profile...</p>
    </div>
  </div>

  <div *ngIf="error" class="container mx-auto py-8">
    <div class="text-center p-8 bg-red-50 rounded-lg shadow-sm">
      <h2 class="text-xl font-semibold mb-4">Error Loading Profile</h2>
      <p class="text-gray-600">{{ error }}</p>
      <button 
        class="mt-6 px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50"
        (click)="browseRecipes()"
      >
        Go Back
      </button>
    </div>
  </div>

  <div *ngIf="profile && !isLoading && !error" class="max-w-5xl mx-auto">
    <!-- Profile header -->
    <div class="bg-white dark:bg-gray-800 p-6 md:p-8 rounded-lg shadow-sm mb-8">
      <div class="flex flex-col md:flex-row md:items-center">
        <div class="h-24 w-24 md:h-32 md:w-32 rounded-full bg-gray-200 flex items-center justify-center overflow-hidden">
          <img *ngIf="profile?.profilePicture" 
               [src]="'http://localhost:3000' + profile.profilePicture" 
               [alt]="profile?.username"
               class="w-full h-full object-cover" />
          <span *ngIf="!profile?.profilePicture" class="text-gray-600 font-semibold text-2xl">
            {{ profile?.username?.[0]?.toUpperCase() || 'U' }}
          </span>
        </div>
        
        <div class="mt-4 md:mt-0 md:ml-8 flex-1">
          <div class="flex flex-col md:flex-row md:items-center justify-between">
            <h1 class="text-2xl font-bold">{{ profile?.username }}</h1>
            
            <div class="flex gap-2 mt-4 md:mt-0">
              <button 
                *ngIf="!isCurrentUser && currentUser"
                (click)="toggleFollow()"
                [class.bg-blue-500]="isFollowing"
                [class.text-white]="isFollowing"
                [class.bg-gray-200]="!isFollowing"
                class="px-4 py-2 rounded-md hover:bg-gray-300"
              >
                {{ isFollowing ? 'Following' : 'Follow' }}
              </button>
            </div>
          </div>
          
          <p *ngIf="profile?.bio" class="text-gray-600 dark:text-gray-300 mt-2">{{ profile?.bio }}</p>
          
          <p *ngIf="profile?.location" class="mt-2 text-gray-600 dark:text-gray-300">
            📍 {{ profile?.location }}
          </p>
          
          <div class="flex gap-6 mt-4">
            <div>
              <span class="font-medium">{{ profile?.recipes?.length || 0 }}</span>
              <span class="text-gray-500 ml-1">Recipes</span>
            </div>
            <div>
              <span class="font-medium">{{ followersCount }}</span>
              <span class="text-gray-500 ml-1">Followers</span>
            </div>
            <div>
              <span class="font-medium">{{ followingCount }}</span>
              <span class="text-gray-500 ml-1">Following</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Tabs -->
    <div class="tabs">
      <div class="tabs-list grid w-full md:w-[400px] grid-cols-2 mb-6">
        <button 
          class="tab-trigger"
          [class.active]="activeTab === 'recipes'"
          (click)="setActiveTab('recipes')"
        >
          Recipes
        </button>
        <button 
          *ngIf="isCurrentUser"
          class="tab-trigger"
          [class.active]="activeTab === 'saved'"
          (click)="setActiveTab('saved')"
        >
          Saved
        </button>
      </div>
      
      <div *ngIf="activeTab === 'recipes'" class="mt-6">
        <div *ngIf="profile?.recipes && (profile?.recipes?.length ?? 0) > 0" 
             class="grid gap-8 grid-cols-1 md:grid-cols-2">
          <div
            *ngFor="let recipe of profile.recipes"
            class="bg-white rounded-lg shadow p-4 cursor-pointer"
            (click)="router.navigate(['/recipe', recipe._id])"
          >
            <img *ngIf="recipe.imageUrl" [src]="recipe.imageUrl" [alt]="recipe.title" class="w-full h-48 object-cover rounded mb-2" />
            <h3 class="font-bold text-lg">{{ recipe.title }}</h3>
            <p class="text-gray-600 text-sm">{{ recipe.description }}</p>
          </div>
        </div>
        <div *ngIf="!profile?.recipes || profile?.recipes?.length === 0" 
             class="text-center py-12 bg-white dark:bg-gray-800 rounded-lg shadow-sm">
          <p class="text-gray-600 dark:text-gray-300">
            {{ isCurrentUser ? "You haven't created any recipes yet." : "This user hasn't created any recipes yet." }}
          </p>
          <button 
            *ngIf="isCurrentUser"
            (click)="createRecipe()"
            class="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md"
          >
            Create Your First Recipe
          </button>
        </div>
      </div>
      
      <div *ngIf="activeTab === 'saved' && isCurrentUser" class="mt-6">
        <div *ngIf="profile?.savedRecipes && (profile?.savedRecipes?.length ?? 0) > 0" 
             class="grid gap-8 grid-cols-1 md:grid-cols-2">
          <div
            *ngFor="let recipe of profile.savedRecipes"
            class="bg-white rounded-lg shadow p-4 cursor-pointer"
            (click)="router.navigate(['/recipe', recipe._id])"
          >
            <img *ngIf="recipe.imageUrl" [src]="recipe.imageUrl" [alt]="recipe.title" class="w-full h-48 object-cover rounded mb-2" />
            <h3 class="font-bold text-lg">{{ recipe.title }}</h3>
            <p class="text-gray-600 text-sm">{{ recipe.description }}</p>
          </div>
        </div>
        <div *ngIf="!profile?.savedRecipes || profile?.savedRecipes?.length === 0" 
             class="text-center py-12 bg-white dark:bg-gray-800 rounded-lg shadow-sm">
          <p class="text-gray-600 dark:text-gray-300">You haven't saved any recipes yet.</p>
          <button 
            (click)="browseRecipes()"
            class="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md"
          >
            Browse Recipes
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// newFront/src/pages/UserProfile.jsx

import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import axios from "axios";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Loader2, UserIcon } from "lucide-react";
import MainLayout from "@/components/Layout/MainLayout";
import ProfileRecipeCard from "@/components/Recipe/ProfileRecipeCard";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

const API_URL = "http://localhost:2059/api/v1";

const UserProfile = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user, isAuthenticated, isLoading: authLoading, getAuthHeader } = useAuth();
  const [profile, setProfile] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isCurrentUser, setIsCurrentUser] = useState(false);

  useEffect(() => {
    // Wait for auth to finish loading before fetching profile
    if (authLoading) return;
    
    const fetchProfile = async () => {
      try {
        if (!isAuthenticated) {
          toast.error('You must be logged in to view profiles');
          navigate('/login');
          return;
        }
        
        setIsLoading(true);
        
        // Determine which user ID to use
        const userId = id || user?._id || user?.id;
        
        if (!userId) {
          throw new Error('User ID not found');
        }
        
        // Check if this is the current user's profile
        setIsCurrentUser(userId === (user?._id || user?.id));

        // Get user profile
        const userResponse = await axios.get(`${API_URL}/users/${userId}`, {
          headers: {
            ...getAuthHeader()
          }
        });

        // Get the user's recipes
        const recipesResponse = await axios.get(`${API_URL}/users/${userId}/recipes`, {
          headers: {
            ...getAuthHeader()
          }
        });

        // Extract user data correctly based on API response structure
        const userData = userResponse.data.data.user || userResponse.data.data.data;
        const recipesData = recipesResponse.data.data;
        
        if (!userData) {
          throw new Error('User data not found');
        }
        
        // Update the profile with both user info and recipes
        setProfile({
          ...userData,
          ...recipesData
        });
        
        // Log the recipes data for debugging
        if (recipesData && recipesData.recipes && recipesData.recipes.length > 0) {
          console.log(`Found ${recipesData.recipes.length} recipes for user`);
        }

        setError(null);
      } catch (err) {
        setError(err.message);
        console.error('Error fetching profile:', err);
      } finally {
        setIsLoading(false);
      }
    };



    fetchProfile();
  }, [id, user, isAuthenticated, getAuthHeader, authLoading, navigate]);

  if (isLoading || authLoading) {
    return (
      <MainLayout>
        <div className="flex items-center justify-center min-h-[80vh]">
          <div className="flex flex-col items-center">
            <Loader2 className="h-12 w-12 animate-spin text-recipe-primary" />
            <p className="mt-4 text-gray-500">Loading profile...</p>
          </div>
        </div>
      </MainLayout>
    );
  }

  if (error) {
    return (
      <MainLayout>
        <div className="container mx-auto py-8">
          <div className="text-center p-8 bg-red-50 rounded-lg shadow-sm">
            <UserIcon className="h-12 w-12 text-red-400 mx-auto mb-4" />
            <h2 className="text-xl font-semibold mb-4">Error Loading Profile</h2>
            <p className="text-gray-600">{error}</p>
            <Button 
              className="mt-6" 
              variant="outline" 
              onClick={() => navigate(-1)}
            >
              Go Back
            </Button>
          </div>
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
    <div className="container mx-auto py-8">
      <div className="max-w-5xl mx-auto">
        {/* Profile header */}
        <div className="bg-white dark:bg-gray-800 p-6 md:p-8 rounded-lg shadow-sm mb-8">
          <div className="flex flex-col md:flex-row md:items-center">
            <Avatar className="h-24 w-24 md:h-32 md:w-32">
              <AvatarImage src={profile?.profilePicture || '/default-avatar.png'} alt={profile?.username} />
              <AvatarFallback>{profile?.username?.[0]?.toUpperCase() || 'U'}</AvatarFallback>
            </Avatar>
            
            <div className="mt-4 md:mt-0 md:ml-8 flex-1">
              <div className="flex flex-col md:flex-row md:items-center justify-between">
                <h1 className="text-2xl font-bold dark:text-white">{profile?.username}</h1>
                
                {isCurrentUser && (
                  <Button 
                    variant="outline" 
                    className="mt-4 md:mt-0"
                    onClick={() => navigate('/settings')}
                  >
                    Edit Profile
                  </Button>
                )}
              </div>
              
              {profile?.bio && (
                <p className="text-gray-600 dark:text-gray-300 mt-2">{profile?.bio}</p>
              )}
              
              {profile?.location && (
                <p className="mt-2 text-gray-600 dark:text-gray-300">📍 {profile?.location}</p>
              )}
              
              <div className="flex gap-4 mt-4">
                <div className="flex items-center">
                  <span className="font-medium mr-1 dark:text-white">{profile?.followers?.length || 0}</span>
                  <span className="text-gray-500 dark:text-gray-400">Followers</span>
                </div>
                <div>
                  <span className="font-medium mr-1 dark:text-white">{profile?.following?.length || 0}</span>
                  <span className="text-gray-500 dark:text-gray-400">Following</span>
                </div>
                <div>
                  <span className="font-medium mr-1 dark:text-white">{profile?.recipes?.length || 0}</span>
                  <span className="text-gray-500 dark:text-gray-400">Recipes</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        {/* Tabs for recipes and saved content */}
        <Tabs defaultValue="recipes">
          <TabsList className="grid w-full md:w-[400px] grid-cols-2">
            <TabsTrigger value="recipes">Recipes</TabsTrigger>
            {isCurrentUser && <TabsTrigger value="saved">Saved</TabsTrigger>}
          </TabsList>
          
          <TabsContent value="recipes" className="mt-6">
            {profile?.recipes?.length > 0 ? (
              <div className="grid gap-8 grid-cols-1 md:grid-cols-2">
                {profile?.recipes?.map(recipe => (
                  console.log(recipe),
                  <ProfileRecipeCard
                    key={recipe._id}
                    recipe={{
                      id: recipe._id,
                      title: recipe.title,
                      description: recipe.description,
                      ingredients: recipe.ingredients,
                      instructions: recipe.instructions.map(step => step.step),
                      cookingTime: recipe.cookingTime,
                      servings: recipe.servings,
                      difficulty: recipe.difficulty,
                      cuisine: recipe.cuisine,
                      author: {
                        id: recipe.author._id,
                        username: recipe.author.username,
                        profilePicture: recipe.author.profilePicture,
                      },
                      imageUrl: recipe.imageUrl || `/uploads/posts/${recipe._id}.jpeg`,
                      createdAt: recipe.createdAt,
                    }}
                  />
                ))}
              </div>
            ) : (
              <div className="text-center py-12 bg-white dark:bg-gray-800 rounded-lg shadow-sm">
                <p className="text-gray-600 dark:text-gray-300">
                  {isCurrentUser ? 'You haven\'t created any recipes yet.' : 'This user hasn\'t created any recipes yet.'}
                </p>
                {isCurrentUser && (
                  <Button className="mt-4" onClick={() => navigate('/create')}>
                    Create Your First Recipe
                  </Button>
                )}
              </div>
            )}
          </TabsContent>
          
          {isCurrentUser && (
            <TabsContent value="saved" className="mt-6">
              {profile?.savedRecipes?.length > 0 ? (
                <div className="grid gap-8 grid-cols-1 md:grid-cols-2">
                  {profile?.savedRecipes?.map(recipe => (
                    <ProfileRecipeCard
                      key={recipe._id}
                      recipe={{
                        id: recipe._id,
                        title: recipe.title,
                        description: recipe.description,
                        ingredients: recipe.ingredients,
                        instructions: recipe.instructions?.map(step => step.step) || [],
                        cookingTime: recipe.cookingTime,
                        servings: recipe.servings,
                        difficulty: recipe.difficulty,
                        cuisine: recipe.cuisine,
                        author: recipe.author ? {
                          id: recipe.author._id,
                          username: recipe.author.username,
                          profilePicture: recipe.author.profilePicture,
                        } : {
                          username: 'Unknown'
                        },
                        imageUrl: recipe.imageUrl || `/uploads/posts/${recipe._id}.jpeg`,
                        createdAt: recipe.createdAt,
                      }}
                    />
                  ))}
                </div>
              ) : (
                <div className="text-center py-12 bg-white dark:bg-gray-800 rounded-lg shadow-sm">
                  <p className="text-gray-600 dark:text-gray-300">You haven't saved any recipes yet.</p>
                  <Button className="mt-4" onClick={() => navigate('/')}>
                    Browse Recipes
                  </Button>
                </div>
              )}
            </TabsContent>
          )}
        </Tabs>
      </div>
    </div>
    </MainLayout>
  );
};

export default UserProfile;
